meta_product_name: "Reduco"
meta_title: "Reduco - The fun way to reduce your carbon footprint"
meta_description: "Save the world why having fun!"
meta_image: "meta_img.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
