meta_product_name: "Reduco"
meta_title: "Reduco - Change isn’t hard if you know what to do!"
meta_description: "Save the world while having fun!"
meta_image: "meta_img.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
